# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectLocation: 'src/Dotnetify/Dotnetify.csproj'
  testProjectLocation: 'test/Dotnetify.Test/Dotnetify.Test.csproj'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install Dotnet SDK'
  inputs:
    version: '2.2.204'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectLocation)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(testProjectLocation)'
    testRunTitle: 'Test Dotnetify'
